repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: make format
        language_version: python3.13
  - repo: local
    hooks:
      - id: prettier-solidity
        name: prettier-solidity
        entry: npx --no-install prettier --write --plugin=prettier-plugin-solidity
        language: system
        types:
          - solidity